name: Deploy Test667

on:
  push:
    branches: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:

  IMAGE: test667
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_ACR_NAME: ${{ vars.AZURE_ACR_NAME }}

  SCORE_HUMANITEC_VERSION: '0.10.2'
  HUMCTL_VERSION: '0.15.0'
  APP_NAME: test667


jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-7`" >> $GITHUB_ENV

      - name: configure azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: login to azure acr
        run: |
          az acr login -n ${{ env.AZURE_ACR_NAME }}
          echo "CONTAINER_REGISTRY=${{ env.AZURE_ACR_NAME }}.azurecr.io" >> "$GITHUB_ENV"


      - run: docker build --platform linux/amd64 . -t $CONTAINER_REGISTRY/$IMAGE:$TAG
      - run: docker push $CONTAINER_REGISTRY/$IMAGE:$TAG

      - uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}

      - name: Inform Humanitec
        run: |-
          humctl create artefact-version \
            --token ${{ secrets.HUMANITEC_TOKEN }} \
            --org ${{ vars.HUMANITEC_ORG_ID }} \
            -t container \
            -n $CONTAINER_REGISTRY/$IMAGE \
            --version $TAG \
            --ref $GITHUB_REF \
            --commit $GITHUB_SHA

      - uses: score-spec/setup-score@v2
        with:
          file: score-humanitec
          version: ${{ env.SCORE_HUMANITEC_VERSION }}

      - name: Deploy using Score
        run: |
          score-humanitec delta \
            --retry \
            --deploy \
            --token ${{ secrets.HUMANITEC_TOKEN }} \
            --org ${{ vars.HUMANITEC_ORG_ID }} \
            --app ${{ env.APP_NAME }} \
            --env development \
            -f score.yaml \
            --extensions humanitec.score.yaml \
            --workload-source-url "https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/score.yaml" \
            --image $CONTAINER_REGISTRY/$IMAGE:$TAG \
            --message "${{ github.event.head_commit.message }}"

